apiVersion: v1
kind: ConfigMap
metadata:
  name: acm-virt-config-13
data:

  ###### Configuration for the acm-dr-virt-install policy ###
  ########################################################

  # backupNS is the ns where velero/oadp is installed on the cluster
  backupNS: acm-app-backup-131
  channel: stable-1.3
  # credentials_hub_secret_name is the name of the Secret resource used by the OADP DPA resource to connect to the storage location
  # hub-secret must be a Secret available under the acm-virt-config namespace. It will be copied over to the backup cluster by the policy
  credentials_hub_secret_name: "hub-secret"
  credentials_name: "cloud-credentials"
  # only VMs with the backup_label_name label will be backed up
  backup_label_name: "cluster.open-cluster-management.io/backup-vm"
  dpa_name: dpa-cls
  dpa_spec: "{
  \"backupLocations\": [
    {
      \"velero\": {
        \"config\": {
          \"profile\": \"default\",
          \"region\": \"us-east-1\"
        },
        \"credential\": {
          \"key\": \"cloud\",
          \"name\": \"cloud-credentials\"
        },
        \"default\": true,
        \"objectStorage\": {
          \"bucket\": \"vb-velero-backup\",
          \"prefix\": \"hub-a\"
        },
        \"provider\": \"aws\"
      }
    }
  ],
  \"configuration\": {
    \"nodeAgent\": {
      \"enable\": true,
      \"uploaderType\": \"kopia\"
    },
    \"velero\": {
      \"defaultPlugins\": [
        \"csi\",       
        \"openshift\",
        \"kubevirt\",
        \"aws\"
      ],
    }
  }
}"
  ##### end configuration for the acm-dr-virt-install policy##

  ###### Configuration for the acm-dr-virt-backup policy ###
  ########################################################
  scheduleTTL: 24h
  # define the schedules to be used by the vm backup; schedule_hub_config_name is the name of the configmap defining all the 
  # supported cron job definitions
  # you should define a ConfigMap named schedule-cron and set values such as : daily_8am: 0 8 * * *
  schedule_hub_config_name: "schedule-cron"
  ## schedule_paused - optional, see velero schedule paused property
  schedule_paused: "true"
  ## schedule_skipImmediately - optional, see velero skipImmediately property
  schedule_skipImmediately: "true"
  ## schedule_useOwnerReferencesInBackup - optional, see velero useOwnerReferencesInBackup property
  schedule_useOwnerReferencesInBackup: "true"
  ## storageLocation is an optional property, if set it should point to the velero BackupStorageLocation resource name to be used by the schedules.
  ## The BackupStorageLocation with this name should exist and with a status of Available.
  # If storageLocation is not set, the default BackupStorageLocation is being used.
  # storageLocation: ""
  ##
  ##### end configuration for the acm-dr-virt-backup policy##


  ###### Configuration for the acm-dr-virt-restore policy ###
  ########################################################
  ## restore_hub_config_name is the name of the ConfigMap defining the restore information
  ## The user should create on the hub a ConfigMap with the name defined below
  ## if this is not a restore operation, set the restoreName in the configName to emmpty 
  restore_hub_config_name: "restore-config"
  ##### end configuration for the acm-dr-virt-restore policy##

