apiVersion: v1
kind: ConfigMap
metadata:
  name: acm-virt-config-13
data:

  ###### Configuration for the acm-virt-policy policy ###
  ########################################################

  # backupNS is the ns where velero/oadp is installed on the cluster
  backupNS: acm-app-backup-131
  channel: stable-1.3
  scheduleTTL: 100h
  # define the schedules to be used by the vm backup; schedule_hub_config_name is the name of the configmap defining all the 
  # supported cron job definitions
  # you should define a ConfigMap named schedule-cron and set values such as : daily_8am: 0 8 * * *
  schedule_hub_config_name: "schedule-cron"
  #
  schedulePaused: "false"
  credentials_hub_secret_name: "hub-secret"
  credentials_name: "cloud-credentials"
  dpa_name: dpa-cls
  # only VMs with the backup_label_name label will be backed up
  backup_label_name: "cluster.open-cluster-management.io/backup-vm"
  dpa_spec: "{
  \"backupLocations\": [
    {
      \"velero\": {
        \"config\": {
          \"profile\": \"default\",
          \"region\": \"us-east-1\"
        },
        \"credential\": {
          \"key\": \"cloud\",
          \"name\": \"cloud-credentials\"
        },
        \"default\": true,
        \"objectStorage\": {
          \"bucket\": \"vb-velero-backup\",
          \"prefix\": \"hub-a\"
        },
        \"provider\": \"aws\"
      }
    }
  ],
  \"configuration\": {
    \"nodeAgent\": {
      \"enable\": true,
      \"uploaderType\": \"kopia\"
    },
    \"velero\": {
      \"defaultPlugins\": [
        \"csi\",       
        \"openshift\",
        \"kubevirt\",
        \"aws\"
      ],
      \"podConfig\": {
        \"resourceAllocations\": {
          \"limits\": {
            \"cpu\": \"2\",
            \"memory\": \"1Gi\"
          },
          \"requests\": {
            \"cpu\": \"500m\",
            \"memory\": \"256Mi\"
          }
        }
      }
    }
  },
}"