apiVersion: v1
kind: ConfigMap
metadata:
  name: acm-virt-config-14
  namespace: open-cluster-management-backup
data:

  ###### Configuration for the acm-dr-virt-install policy ###
  ########################################################

  # backupNS is the ns where velero/oadp is installed on the cluster
  channel: stable-1.4
  dpa_spec: '{ backupLocations: [ { velero: { config: { profile: default, region: us-east-1-change-me, }, credential: { key: cloud, name: cloud-credentials, }, default: true, objectStorage: { bucket: velero-bucket-change-me, prefix: velero-prefix-change-me, }, provider: aws } } ], configuration: { nodeAgent: { enable: true, uploaderType: kopia, }, velero: { defaultPlugins: [ csi, openshift, kubevirt, aws ], } }, }'
  backupNS: open-cluster-management-backup
  restore_hub_config_name: acm-dr-virt-restore-config
  credentials_hub_secret_name: cloud-credentials
  credentials_name: cloud-credentials
  dpa_name: dpa-vm-policy
  scheduleTTL: 120h
  schedule_hub_config_name: acm-dr-virt-schedule-cron
