#
# This configmap is used by all three policies
# and specifies the configuration required to install velero, backup or restore
#
# This config is set to use snapshotVolumes for backing up PVs; this option works only if 
# your backup and restore clusters use the same StorageClass 
# and the restore cluster can access the region/location where the volume snapshot are stored
# 
apiVersion: v1
kind: ConfigMap
metadata:
  name: acm-virt-config
data:

  ###### Configuration for the acm-virt-policy policy ###
  ########################################################

  # backupNS is the ns where velero/oadp is installed on the cluster
  backupNS: acm-app-backup
  channel: stable-1.3
  scheduleTTL: 100h
  scheduleCron: "0 */3 * * *"
  schedulePaused: "false"
  credentials_hub_secret_name: "hub-secret"
  credentials_name: "cloud-credentials"
  dpa_name: dpa-hub-a
  dpa_spec: "{
  \"backupLocations\": [
    {
      \"velero\": {
        \"config\": {
          \"profile\": \"default\",
          \"region\": \"us-east-1\"
        },
        \"credential\": {
          \"key\": \"cloud\",
          \"name\": \"cloud-credentials\"
        },
        \"default\": true,
        \"objectStorage\": {
          \"bucket\": \"vb-velero-backup\",
          \"prefix\": \"hub-a\"
        },
        \"provider\": \"aws\"
      }
    }
  ],
  \"configuration\": {
    \"nodeAgent\": {
      \"enable\": true,
      \"uploaderType\": \"kopia\"
    },
    \"velero\": {
      \"defaultPlugins\": [
        \"csi\",       
        \"openshift\",
        \"kubevirt\",
        \"aws\"
      ],
      \"podConfig\": {
        \"resourceAllocations\": {
          \"limits\": {
            \"cpu\": \"2\",
            \"memory\": \"1Gi\"
          },
          \"requests\": {
            \"cpu\": \"500m\",
            \"memory\": \"256Mi\"
          }
        }
      }
    }
  },
}"