apiVersion: v1
kind: ConfigMap
metadata:
  name: restore-config-cls-13
data:

  ###### Configuration for the acm-dr-virt-restore policy, defining the vms to be restored on this cluster ###
  ########################################################

  # define the name of the velero restore, for example acm-restore-twice-a-day-20241208155210
  # set this to "" if this is not a restore operation acm-rho-virt-schedule-twice-a-day-20241211120055
  restoreName: ""
  # define the list of VM UID to be restored; enter the UIDs separated by space
  vmsUID: "b0ed31e9-ee17-4a59-9aa5-76b15a10ee42 uid2"
  # backupName is the name of the backup to restore
  backupName: acm-rho-virt-schedule-twice-a-day-20241211120055
  # id of the cluster where the restore should be run; used to enforce the target for the restore operation, in case multiple clusters share the same acm-virt configMap
  restoreClusterID: ""

