apiVersion: v1
kind: ConfigMap
metadata:
  name: restore-config
data:

  ###### Configuration for the acm-dr-virt-restore policy, defining the vms to be restored on this cluster ###
  ########################################################

  # define the name of the velero restore
  restoreName: "acm-restore-1"
  # define the list of VM UID to be restored; enter the UIDs separated by space
  vmsUID: "uid1 uid2"
  # backupName is the name of the backup to restore
  backupName: acm-rho-virt-schedule-20241031214304
