apiVersion: v1
kind: ConfigMap
metadata:
  name: restore-config
data:

  ###### Configuration for the acm-dr-virt-restore policy, defining the vms to be restored on this cluster ###
  ########################################################

  # define the name of the velero restore
  restoreName: "acm-restore-1"
  # define the list of VM UID to be restored; enter the UIDs separated by space
  vmsUID: "b0ed31e9-ee17-4a59-9aa5-76b15a10ee42 uid2"
  # backupName is the name of the backup to restore
  backupName: acm-rho-virt-schedule-twice-a-day-20241208155210
