resources:
- ./input/restic/hdr-app-configmap.yaml # optionally, use input/pv-snap 
- acm-app-backup-policy-set.yaml
- acm-app-restore-policy-set.yaml
- oadp-hdr-app-install.yaml
- oadp-hdr-app-backup.yaml
- oadp-hdr-app-restore.yaml
