resources:
# Update all settings with valid values before applying the `hdr-app-configmap` resource on the hub.
# use ./input/pv-snap/hdr-app-configmap.yaml if you want to use volume snapshots instead of restic
- ./input/restic/hdr-app-configmap.yaml 
- ./policy-sets/acm-app-backup-policy-set.yaml
- ./policy-sets/acm-app-restore-policy-set.yaml
- ./policies/oadp-hdr-app-install.yaml
- ./policies/oadp-hdr-app-backup.yaml
- ./policies/oadp-hdr-app-restore.yaml
