kind: ConfigMap
apiVersion: v1
metadata:
  name: volsync-acm-config
  namespace: openshift-operators
data:
  channel_name : "volsync-channel"
  channel_ns: "volsync-ns"
  channel_path : "https://backube.github.io/helm-charts"
  subscription_ns: "volsync-ns"
  default_version: "0.11.0-rc.1"
  package_name: "volsync"
  addon_name_volsync: "volsync"
