apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: acm-dr-pvc-backup-policyset
  namespace: open-cluster-management-backup
spec:
  description: |
    Backup virtualmachines.kubevirt.io resources on hub or OpenShift managed clusters, using OADP. 
    Supports Container Storage Interface (CSI) and (CSI) with DataMover storage, File system and Volume snapshot options are not supported.
  policies:
    - acm-dr-pvc-backup
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: acm-dr-pvc-placement
  namespace: open-cluster-management-backup
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'acm-virt-config'
              operator: 'Exists'    
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: acm-dr-pvc-placement-binding
  namespace: open-cluster-management-backup
placementRef:
  name: acm-dr-pvc-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: acm-dr-pvc-backup-policyset
    apiGroup: policy.open-cluster-management.io
    kind: PolicySet