apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: volsync-channel
  namespace: volsync-ns
spec:
  pathname: 'https://raw.githubusercontent.com/fxiang1/app-samples/main'
  type: HelmRepo