Deploy helm app on EKS using the helm subscription
https://console-openshift-console.apps.app-aws-east1-412-sno-2xl-2x6qk.dev11.red-chesterfield.com/multicloud/applications/details/mortgage/mortgage/topology


Steps:
1. create the Channel resource ( the repo where the channel points to must have an index.yaml file containing the helm descriptions - this is all that this repo requires )

Sample: https://github.com/fxiang1/app-samples/blob/main/index.yaml

apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: volsync-channel
  namespace: volsync-ns
spec:
  pathname: 'https://raw.githubusercontent.com/fxiang1/app-samples/main'
  type: HelmRepo


2. When a volsync addon is created, it should create a Subscription + Placement rule 

apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: volsync-subscription-0.10.0
  namespace: volsync
spec:
  channel: >-
    volsync-ns/volsync-channel
  name: mortgage
  packageFilter:
    version: 0.10.0
  packageOverrides:
    - packageAlias: volsync
      packageName: volsync
  placement:
    placementRef:
      kind: Placement
      name: volsync-placement-0.10.0


apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: volsync-placement-0.10.0
  namespace: volsync
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: volsync
              operator: In
              values:
                - 0.10.0


