---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: volsync-subscription-1.0.3
  namespace: volsync
spec:
  channel: >-
    volsync-ns/volsync-channel
  name: mortgage
  packageFilter:
    version: 1.0.3
  packageOverrides:
    - packageAlias: mortgage
      packageName: mortgage
  placement:
    placementRef:
      kind: Placement
      name: volsync-placement-1.0.3
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: volsync-placement-1.0.3
  namespace: volsync
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: volsync
              operator: In
              values:
                - 1.0.3
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  namespace: volsync
  name: global
spec:
  clusterSet: global
