---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: volsync-subscription-0.10.0
  namespace: volsync
spec:
  channel: >-
    volsync-ns/volsync-channel
  name: mortgage
  packageFilter:
    version: 0.10.0
  packageOverrides:
    - packageAlias: volsync
      packageName: volsync
  placement:
    placementRef:
      kind: Placement
      name: volsync-placement-0.10.0
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: volsync-placement-0.10.0
  namespace: volsync
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: volsync
              operator: In
              values:
                - 0.10.0
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  namespace: volsync
  name: global
spec:
  clusterSet: global