apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: acm-app-restore-placement
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
          - {key: acm-pv-dr, operator: In, values: ["restore"]}
