apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: acm-dr-virt-restore
  annotations:
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous Monitoring
    policy.open-cluster-management.io/standards: NIST SP 800-53
spec:
  dependencies:
  - apiVersion: policy.open-cluster-management.io/v1
    compliance: Compliant
    kind: Policy
    name: acm-dr-virt-install
  disabled: false
  policy-templates:                                                                                                                                             
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: create-restore-config
        spec:
          object-templates-raw: |
            {{- /* ns is the namespace for the OADP deployment  */ -}}
            {{- $ns := "{{hub fromConfigMap "" (printf "%s" (index .ManagedClusterLabels "acm-virt-config")) "backupNS" hub}}" }}
            {{- $hub_restore_name := "{{hub fromConfigMap "" (printf "%s" (index .ManagedClusterLabels "acm-virt-config")) "restore_hub_config_name" hub}}" }}

            {{- /* cls_configmap_name is name of the main config map, copied over to the cluster by the install policy  */ -}}
            {{- $cls_configmap_name := "acm-virt-config-cls" }}

            {{ if not (eq "" $hub_restore_name) }}
              - complianceType: mustonlyhave
                objectDefinition:
                  apiVersion: v1
                  kind: ConfigMap
                  metadata:
                    name: {{ $cls_configmap_name }}
                    namespace: {{ $ns }}
                    data: '{{hub copyConfigMapData "" (fromConfigMap "" (printf "%s" (index .ManagedClusterLabels "acm-virt-config")) "restore_hub_config_name") hub}}'
            {{- end }}

          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-restore-config-exists
        spec:
          object-templates-raw: |
            {{- /* ns is the namespace for the OADP deployment  */ -}}
            {{- $ns := "{{hub fromConfigMap "" (printf "%s" (index .ManagedClusterLabels "acm-virt-config")) "backupNS" hub}}" }}
            {{- $hub_restore_name := "{{hub fromConfigMap "" (printf "%s" (index .ManagedClusterLabels "acm-virt-config")) "restore_hub_config_name" hub}}" }}

            {{ if not (eq "" $hub_restore_name) }}
              - complianceType: musthave
                objectDefinition:
                  apiVersion: v1
                  kind: ConfigMap
                  metadata:
                    name: "acm-virt-config-cls"
                    namespace: {{ $ns }}
            {{- end }}
          customMessage:
            noncompliant: |-
              The restore property restore_hub_config_name is defined by the acm-virt-config ConfigMap but there is no ConfigMap with that name.
              Make sure you create the restore ConfigMap or, if this is not a restore operation, remove the restore_hub_config_name property.
          remediationAction: inform
          severity: low 
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-restore-status-completed
        spec:
          object-templates-raw: |
            {{- /* check if this is a hub, acm installed  */ -}}
            {{- $acm_crd_name := "multiclusterhubs.operator.open-cluster-management.io" }}
          remediationAction: inform
          severity: low  
