kind: ConfigMap
apiVersion: v1
metadata:
  name: volsync-config
  namespace: open-cluster-management-backup
  labels:
    cluster.open-cluster-management.io/backup: volsync
data:
  cacheCapacity: 2Gi
  copyMethod: Snapshot
  pruneIntervalDays: '2'
  repository: restic-secret-vb
  retain_daily: '2'
  retain_hourly: '3'
  retain_monthly: '1'
  trigger_schedule: 0 */1 * * *